use_frameworks!

platform :ios, '9.0'

target 'ThinkingDataPushExtension_Example' do
  pod 'ThinkingDataPushExtension', :path => '../'

  target 'ThinkingDataPushExtension_Tests' do
    inherit! :search_paths

    
  end
end
